# Attention mechanizmus a transformery

Na minulom cvičení sme sa pozreli na to, ako dokážeme využiť rekurentné neurónové siete na spracovanie prirodzeného jazyka v kontexte analýzy sentimentu, a generovania textu. Tiež sme zadefinovali rôzne typy úloh so sekvenčnými dátami, okrem iného aj generovanie many-to-many, kde vstupom je sekvencia údajov a na výstupe sieť tiež vyprodukuje sekvenciu, práve preto sa takýto prípad použitia nazýva aj **sequence-to-sequence** (**seq2seq**). Špeciálnym prípadom seq2seq úloh bol prípad, kde sme výstupnú sekvenciu generovali so skĺzom, čo znamenalo, že sieť musela najprv spracovať všetky vstupné údaje, až neskôr dokázala vygenerovať výstup. Nevýhodou takéhoto prístupu je, že posledný skrytý stav, na základe ktorého sa vygeneruje výstup, musí v sebe obsahovať všetky relevantné informácie z celého vstupu.

Na dnešnom cvičení sa pozrieme na to, ako dokáže využitie attention mechanizmu pomôcť pri riešení tohto problému. Následne sa budeme zaoberať self-attention prístupom, a dostaneme sa k transformerom a veľkým jazykovým modelom.

## Attention mechanizmus v RNN

Attention mechanizmus umožňuje rekurentnej sieti pristupovať k všetkým vstupným dátam pri každom kroku generovania výstupu. Takýto prístup však môže byť priveľký, a práve preto zavedieme nové typy váh, tzv. *attention váhy*, ktoré vyjadrujú dôležitosť daného vstupu pre generovanie výstupu v danom časovom okamihu.

Formálne môžeme povedať, že pre danú vstupnú sekvenciu $(x^{(1)}, x^{(2)}, ... x^{(T)})$ attention mechanizmus priradí každému prvku $x^{(i)}$, resp. jeho skrytej reprezentácii, váhu, a tak umožní modelu rozhodnúť sa, na ktorú časť sekvencie sa má sústrediť.

Nasledujúci obrázok znázorňuje základný princíp integrovania attention mechanizmu do rekurentnej siete:

![](lab08/attention-rnn.jpg)

### Obojsmerná rekurentná sieť

Prvým komponentom riešenia je obojsmerná rekurentná sieť, ktorá generuje tzv. *context vector* $c_{i}$, čo predstavuje rozšírenú verziu vstupného vektora $x^{(i)}$ o informácie zo všetkých vstupných prvkov. Prvá sieť je obojsmerná z toho dôvodu, že vstupné údaje spracuje aj v pôvodnom poradí $(1...T)$ ako aj $(T...1)$. Motiváciou takéhoto prístupu je zámer brať do úvahy možný vplyv nasledujúcich prvkov vstupu na aktuálny vstup.

Vzhľadom na dvojsmerné spracovanie vstupu, neurónová sieť vygeneruje dva skryté stavy pre každý vstup: $h_{F}^{(i)}$ pre dopredný prechod a $h_{B}^{(i)}$ pre spätný prechod. Tieto dva stavy sa spoja konkatenáciou a tak vznikne celkový skrytý stav $h^{(i)}$.

### Generovanie výstupu

Druhá neurónová sieť, ktorá generuje výstup, okrem skrytých stavov dostane aj *context vector*, ktorý je vypočítaný nasledovne:

$$c_{i} = \sum_{j=1}^{T} \alpha_{ij} h^{(i)},$$

kde $\alpha_{ij}$ predstavuje attention váhu pre vstupnú postupnosť $j = (1...T)$ pre *i*-tý vstupný prvok. To znamená, že každý vstupný údaj má pridelenú vlastnú sadu attention váh.

Druhá rekurentná neurónová sieť potom generuje výstup na základe vstupných informácií pomocou vlastných skrytých stavov $s^{(i)}$, ktoré závisia od predošlého skrytého stavu $s^{(i - 1)}$, od predošlého očakávaného výstupného slova $y^{(i - 1)}$ a od *context vector*a $c^{(i)}$. Očakávaný výstup je samozrejme dostupný iba počas trénovania, počas inferencie sa použije predikovaný výstup z predošlého kroku, t.j. $o^{(i - 1)}$.

### Výpočet attention váh

Každá attention váha je definovaná pre vstup (anotácie zo skrytých stavov) a výstup (kontext), a práve preto používame dva indexy (*j* pre vstup, *i* pre výstup). Váhu vypočítame normalizáciou *alignment skóre* $e_{ij}$, ktorá vyjadruje, ako veľmi je vstup okolo pozície *j* v súlade s výstupom na pozícii *i*.

$$\alpha _{ij} = \frac{\exp(e_{ij})}{\sum_{k=1}^{T} \exp(e_{ik})}$$

Normalizácia prebieha rovnako ako pri softmax aktivácii, to znamená, že attention váhy pre výstup *i* budú mať súčet 1.

## Self-attention mechanizmus

Transformery na rozdiel od predošlej rekurentnej siete používajú self-attention mechanizmus, ktorý nevyžaduje rekurentný proces, teda transformer dokáže spracovať vstupnú sekvenciu v jednom kroku a nemusí na to využiť iteráciu. Ďalším zásadným rozdielom je, že kým attention mechanizmus akokeby prepájal dve siete (enkóder a dekóder), tak sa self-attention zaoberá iba so vstupmi a neprepája ich na iný modul.

### Self-attention bez učenia

Cieľom self-attention mechanizmu je namodelovať súvislosti medzi jednotlivými vstupnými vektormi $x^{(1)}, x^{(2)}, ... x^{(T)}$, ktoré bude reprezentovať vo výstupných vektoroch $z^{(1)}, z^{(2)}, ... z^{(T)}$ (označenie $o^{(i)}$ ponecháme pre celkový výstup siete). Výpočet pozostáva z troch fáz:

1. výpočet váh dôležitosti na základe podobnosti všetkých prvkov vstupnej sekvencie k aktuálnemu prvku (vstup bol namapovaný do číselnej podoby, a prešiel embeddingom)

$$\omega _{ij} = {x^{(i)}}^{T} x^{(j)}$$

2. normalizácia váh (zvyčajne pomocou softmax)

$$\alpha _{ij} = \frac{\exp(\omega_{ij})}{\sum_{j=1}^{T} \exp(\omega_{ij})}$$

3. výpočet hodnoty attention

$$z^{(i)} = \sum_{j=1}^{T} \alpha_{ij} x^{(j)}$$

In [1]:
import torch

sentence = torch.tensor(
    [0,  # please
     7,  # help
     1,  # me
     2,  # translate
     5,  # this
     6]  # sentence
)
print(sentence)

tensor([0, 7, 1, 2, 5, 6])


In [2]:
torch.manual_seed(123)
embed = torch.nn.Embedding(10, 16)
embedded_sentence = embed(sentence).detach()
print(embedded_sentence)

tensor([[ 3.3737e-01, -1.7778e-01, -3.0353e-01, -5.8801e-01,  3.4861e-01,
          6.6034e-01, -2.1964e-01, -3.7917e-01,  7.6711e-01, -1.1925e+00,
          6.9835e-01, -1.4097e+00,  1.7938e-01,  1.8951e+00,  4.9545e-01,
          2.6920e-01],
        [-9.4053e-01, -4.6806e-01,  1.0322e+00, -2.8300e-01,  4.9275e-01,
         -1.4078e-02, -2.7466e-01, -7.6409e-01,  1.3966e+00, -9.9491e-01,
         -1.5822e-03,  1.2471e+00, -7.7105e-02,  1.2774e+00, -1.4596e+00,
         -2.1595e+00],
        [-7.7020e-02, -1.0205e+00, -1.6896e-01,  9.1776e-01,  1.5810e+00,
          1.3010e+00,  1.2753e+00, -2.0095e-01,  4.9647e-01, -1.5723e+00,
          9.6657e-01, -1.1481e+00, -1.1589e+00,  3.2547e-01, -6.3151e-01,
         -2.8400e+00],
        [-1.3250e+00,  1.7843e-01, -2.1338e+00,  1.0524e+00, -3.8848e-01,
         -9.3435e-01, -4.9914e-01, -1.0867e+00,  8.8054e-01,  1.5542e+00,
          6.2662e-01, -1.7549e-01,  9.8284e-02, -9.3507e-02,  2.6621e-01,
         -5.8504e-01],
        [ 2.5529e-01

In [3]:
# 1. krok - výpočet váh dôležitosti
omega_mat = embedded_sentence.matmul(embedded_sentence.T)
print(omega_mat)

tensor([[ 9.7601,  1.7326,  4.7543, -1.3587,  0.4752, -1.6717],
        [ 1.7326, 16.0787,  9.0642, -0.3370,  1.1368,  1.1972],
        [ 4.7543,  9.0642, 22.6615, -0.8519,  7.7799,  2.7483],
        [-1.3587, -0.3370, -0.8519, 13.9473, -1.4198, 10.9659],
        [ 0.4752,  1.1368,  7.7799, -1.4198, 13.7511, -6.8568],
        [-1.6717,  1.1972,  2.7483, 10.9659, -6.8568, 24.6738]])


In [4]:
# 2. krok - normalizácia
import torch.nn.functional as F

attention_weights = F.softmax(omega_mat, dim=1)
print(attention_weights)
print(attention_weights.sum(axis=1))

tensor([[9.9291e-01, 3.2405e-04, 6.6516e-03, 1.4726e-05, 9.2154e-05, 1.0768e-05],
        [5.8773e-07, 9.9910e-01, 8.9788e-04, 7.4187e-08, 3.2391e-07, 3.4407e-07],
        [1.6712e-08, 1.2438e-06, 1.0000e+00, 6.1412e-11, 3.4437e-07, 2.2482e-09],
        [2.1438e-07, 5.9550e-07, 3.5585e-07, 9.5173e-01, 2.0167e-07, 4.8273e-02],
        [1.7110e-06, 3.3158e-06, 2.5448e-03, 2.5719e-07, 9.9745e-01, 1.1195e-09],
        [3.6165e-12, 6.3713e-11, 3.0052e-10, 1.1136e-06, 2.0250e-14, 1.0000e+00]])
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [5]:
# 3. krok - výpočet kontext vektorov
context_vectors = torch.matmul(attention_weights, embedded_sentence)
print(context_vectors)

tensor([[ 3.3414e-01, -1.8352e-01, -3.0213e-01, -5.7773e-01,  3.5677e-01,
          6.6433e-01, -2.0970e-01, -3.7824e-01,  7.6531e-01, -1.1949e+00,
          6.9991e-01, -1.4070e+00,  1.7030e-01,  1.8842e+00,  4.8731e-01,
          2.4757e-01],
        [-9.3975e-01, -4.6856e-01,  1.0311e+00, -2.8192e-01,  4.9373e-01,
         -1.2897e-02, -2.7327e-01, -7.6359e-01,  1.3958e+00, -9.9543e-01,
         -7.1235e-04,  1.2449e+00, -7.8077e-02,  1.2765e+00, -1.4589e+00,
         -2.1601e+00],
        [-7.7021e-02, -1.0205e+00, -1.6895e-01,  9.1776e-01,  1.5810e+00,
          1.3010e+00,  1.2753e+00, -2.0095e-01,  4.9647e-01, -1.5723e+00,
          9.6657e-01, -1.1481e+00, -1.1589e+00,  3.2547e-01, -6.3151e-01,
         -2.8400e+00],
        [-1.3679e+00,  1.0613e-01, -2.1317e+00,  1.0480e+00, -3.7127e-01,
         -9.1236e-01, -4.3803e-01, -1.0329e+00,  9.3424e-01,  1.5453e+00,
          5.7219e-01, -1.8050e-01, -6.0394e-03, -8.8685e-02,  2.0559e-01,
         -5.2293e-01],
        [ 2.5444e-01

### Self-attention s učením

Existuje niekoľko foriem attention mechanizmu, jedna z najvýznamnejších je **scaled dot-product attention** použitý aj v transformeroch. Hore uvedený attention mechanizmus rozširuje o tri matice váh, ktoré sú trénovateľné:

* query sequence: $q^{(i)} = U_{q} x^{(i)}$
* key sequence: $k^{(i)} = U_{k} x^{(i)}$
* value sequence: $v^{(i)} = U_{v} x^{(i)}$.

Tieto matice zvyčajne majú rozmery totožné s embeddingom, teda $d_q = d_k = d_v = d$, kde *d* je dĺžka vektoru jedného vstupu. V tejto forme attention mechanizmu výpočet výstupu prebieha nasledovne:

1. výpočet váh dôležitosti pomocou query a key postupností

$$\omega _{ij} = {q^{(i)}}^{T} k^{(j)}$$

2. normalizácia váh (zvyčajne pomocou softmax) na približne rovnakú dĺžku (zvyčajne $m = d_k$)

$$\alpha_{ij} = softmax (\frac{\omega_{ij}}{\sqrt{m}})$$

3. výpočet hodnoty attention

$$z^{(i)} = \sum_{j=1}^{T} \alpha_{ij} v^{(j)}$$

In [6]:
torch.manual_seed(123)
d = embedded_sentence.shape[1]
U_q = torch.rand(d, d)
U_k = torch.rand(d, d)
U_v = torch.rand(d, d)

queries = U_q.matmul(embedded_sentence.T).T
keys = U_k.matmul(embedded_sentence.T).T
values = U_v.matmul(embedded_sentence.T).T

In [7]:
# 1. krok - výpočet váh dôležitosti
omega_2 = queries[1].matmul(keys.T)
print(omega_2)

tensor([-25.1623,   9.3602,  14.3667,  32.1482,  53.8976,  46.6626])


In [8]:
# 2. krok - normalizácia
attention_weights_2 = F.softmax(omega_2 / d**0.5, dim=0)
print(attention_weights_2)

tensor([2.2317e-09, 1.2499e-05, 4.3696e-05, 3.7242e-03, 8.5596e-01, 1.4026e-01])


In [9]:
# 3. krok - výpočet kontext vektorov
context_vector_2 = attention_weights_2.matmul(values)
print(context_vector_2)

tensor([-1.2226, -3.4387, -4.3928, -5.2125, -1.1249, -3.3041, -1.4316, -3.2765,
        -2.5114, -2.6105, -1.5793, -2.8433, -2.4142, -0.3998, -1.9917, -3.3499])


## Transformery

Transformery boli predstavené v roku 2017 na konferencii NeurIPS. Sú síce založené na koncepte attentionu pre rekurentné siete, avšak fungujú omnoho efektívnejšie aj vďaka tomu, že vynechajú rekurentnú časť. Základná architektúra transformerov je znázornená nižšie:

![](lab08/transformer.jpg)

### Enkóder

Úlohou prvej časti transformera, teda enkódera, je namapovať vstupnú sekvenciu $X = (x^{(1)}, x^{(2)}, ... x^{(T)})$ do spojitej reprezentácie $Z = (z^{(1)}, z^{(2)}, ... z^{(T)})$. V pôvodnom článku sa enkóder skladal zo šiestich identických vrstiev, ich počet je však ďalším hyperparametrom.

Dôležitým rozdielom oproti predošlým mechanizmom je použitie **multi-head self-attention**, čo je v podstate niekoľkonásobná paralelná aplikácia **scaled dot-product attention** mechanizmu, akokeby sme použili viac konvolučných filtrov v jednej vrstve. Jeden *head* komponent sa skladá z troch matíc (queries, keys a values), pri multi-head self-attention teda vygenerujeme niekoľko takýchto matíc, a pre každú z nich vypočítame výstup podobným spôsobom, ako sme to robili pred tým. Rovnako ako pri konvolúcii, jednotlivé *head* komponenty sa dokážu sústrediť na rôzne časti vstupných údajov.

Následne tieto vektory spojíme konkatenáciou do tvaru $d_v \times h$, kde *h* je počet head komponentov. Tento rozšírený vektor upravíme do pôvodného tvaru cez plne prepojenú vrstvu.

### Dekóder

Dekóder pracuje rovnako s niekoľkými identickými blokmi, avšak v jednom bloku použijeme ďalší typ attention mechanizmu, a to **masked multi-head attention**. Maskovanie dosiahneme napríklad prekrytím slov, ktoré nasledujú po aktuálnom slove, čím sa snažíme nasimulovať fungovanie modelu počas inferencie. Takéto maskovanie však aplikujeme iba na postupnosť výstupov, vstupné údaje naďalej sú spracované obojsmerne cez enkóder.

Vstupom do dekóder bloku sú výstup enkódera, ako aj zakódovaný výstup z predošlého kroku, ktorý prechádza práve masked attention mechanizmom. Po ďalšom prechode multi-head attention mechanizmom plne prepojená vrstva vygeneruje výstup dekódera, teda pravdepodobnosti pridelené jednotlivým výstupným slovám. Vybrané potom bude slovo s najväčšou predikovanou pravdepodobnosťou.

### Pozičné enkódovanie

Dôležitou súčasťou transformerov je použitie pozičného enkódovania, ktoré slúži na zachytávanie informácií o poradí slov vo vstupe. Tento prístup je potrebný z toho dôvodu, že attention mechanizmy sú invariantné voči permutáciám, čo by znamenalo, že by transformery ignorovali poradie slov, čo môže spôsobiť problémy, napr.:

1. Mary gave Bertie a flower.
2. Bertie gave Mary a flower.

Pôvodné transformery použili sínusoidálne enkódovanie, ktoré umožní, aby rovnaké slová na rôznych pozíciach mali trošku odlišné enkódovanie cez pripočítanie vektoru k vstupnému vektoru:

$$PE_{(i, 2k)} = \sin (pos / 10000^{2k/d_{model}}),$$

kde *i* je pozícia slova a *k* je dĺžka embeddingu vstupných slov (aby sme vedeli sčítať vektory). Okrem uvedeného absolútneho enkódingu môžeme použiť aj relatívne, ktoré zohľadňuje iba relatívnu pozíciu slov, a tým pádom je invariantné k posunom viet v celkovom texte.

Okrem pozičného enkódovania, transformery používajú aj normalizáciu vrstvy (*layer normalization*), čo umožňuje efektívnejšiu paralelizáciu v porovnaní so štandardným BatchNormom.

## Veľké jazykové modely

Kľúčovú úlohu pri úspechu veľkých jazykových modelov založených na transformeroch zohrával **self-supervised learning**, alebo **unsupervised pre-training**, ktorý využíva špecifické vlastnosti textových údajov pri trénovaní. To znamená, že nepotrebujeme veľké množstvo olabelovaných dát, namiesto toho model natrénujeme napríklad na predikciu ďalšieho slova (vždy prístupné pri textoch), a neskôr doladíme na konkrétny príklad použitia s menším množstvom dát.

Použitie jazykových modelov zvyčajne nasleduje dva prístupy: prístup založený na príznakoch, alebo doladenie. Príkladom prístupu založeného na príznakoch je model **ELMo**, ktorý slúži na embedding a bol trénovaný náhodným maskovaním 15 percent slov (teda neboli zakryté nasledujúce slová, ale náhodné). Pri doladení priamo aktualizujeme váhy predtrénovaného modelu a topológiu zvyčajne rozšírime o minimálne jednu (výstupnú) vrstvu.

Najpoužívanejšie jazkové modely sú GPT, BERT a BART.

### GPT

GPT (**Generative Pre-trained Transformer**) je séria jazykových modelov primárne určených pre generovanie textu. GPT-1 (110M parametrov), ktorý vyšiel v roku 2018, sa skladá iba z dekódera bez enkóderovej časti, a z ďalšej vrstvy, ktorá sa používa počas ladenia modelu. GPT-1 spracuje text iba v jednom smere, to znamená, že pri predikcii nasledujúceho slova sa spolieha iba na predchádzajúce slová, generovanie prebieha po jednotlivých slovách. Počas trénovania sa stále použijú správne slová, počas inferencie do ďalšieho kroku je pridané modelom vygenerované slovo.

Silnou stránkou GPT-1 modelu bola výkonnosť na **zero-shot** úlohách, teda na úlohách, z ktorých nevidel trénovacie príklady. Práve táto adaptabilita inšpirovala vývojárov na ďalšiu generalizáciu modelu vo verzii GPT-2 (1,5B parametrov) cez pridanie kontextu k vstupu, ako napríklad inštrukcia *translate to Slovak* pri strojovom preklade.

Verzia GPT-3 (175B parametrov) sa nesústreďovala na zero-shot, ale na **few-shot** úlohy, t.j. model má k dispozícii malý počet príkladov, z ktorých musí zovšeobecniť rýchlo svoje správanie, čo lepšie zodpovedá ľudskému učeniu. Ďalším rozdielom oproti GPT-2 je použitie **sparse attention**, kde sa model sústredí iba na podmnožinu všetkých prvkov s limitovaným počtom.

GPT modely môžu byť použité aj pre klasifikáciu, v tomto prípade vstup musí byť tokenizovaný a postupne zadaný do modelu. Model je rozšírený o spomínanú vrstvu, ktorá na výstupe má jednu (alebo niekoľko) hodnotu. Pre komplikovanejšie prípady použitia, ako je odpovedanie otázok, je potrebné špeciálne predspracovanie údajov.

### BERT

BERT (**Bidirectional Encoder Representations from Transformers** - 345M parametrov), na rozdiel od GPT, obsahuje enkóder využívajúci obojsmerné spracovanie vstupu (resp. spracovanie bez smeru, keďže celý vstup sa spracuje naraz). To znamená, že enkódovanie slova závisí od predošlých aj nasledujúcich slov, čo spôsobuje kvalitnejšie enkódovanie pre úlohy ako klasifikácia.

BERT využíva tri typy embeddingu: už spomínané token a pozičné embeddingy, ako aj segmentový embedding, ktorý identifikuje vety alebo väčšie celky slov. Potreba embeddingu súvisí s trénovaním BERTu, ktoré prebiehalo aj spôsobom *next-sentence prediction*, kde model musí povedať, či dvojica viet nasleduje po sebe alebo nie.

Okrem toho BERT využíval aj maskovanie pri trénovaní, pričom náhodne bolo vybratých 15 percent tokenov na zamaskovanie, z toho 10 percent bolo ponechaných v pôvodnom stave, 10 percent bolo zamenených za iné náhodné slovo, a zvyšok bol zakrytý.

Pri klasifikácii vo vstupe sa použije špeciálny token `[CLS]`, ktorý je potom nahradený modelom podľa výsledku klasifikácie. Typickými prípadmi použitia BERT modelu sú klasifikácia dvojice viet, klasifikácia jednej vety, odpovedanie na otázky a tagovanie jednej vety. Prvé dve vyžadujú minimálne zmeny v architektúre, kým ostatné vyžadujú úpravu výstupu pre tokeny (predikcie sú generované pre každý jeden token a nie pre celú vetu).

### BART

BART (**Bidirectional and Auto-Regressive Transformer**) kombinuje výhody GPT pre generovanie textu a BERT pre klasifikáciu tak, že obsahuje aj obojsmerný enkóder ako aj autoregresívny dekóder, ktorý funguje zľava doprava. Veľkým rozdielom oproti pôvodnému transformeru je to, že BART používa iba vstupné údaje ako vstup, teda nevyžaduje očakávaný výstup (v pôvodnom transformeri text v inom jazyku). Očakávaný výstup sa stále používa pri výpočte chyby, ale nie je priamym vstupom do modelu.

V BART modeli, vstup je najprv skorumpovaný a následne enkódovaný. Enkódovaný vstup je potom dodaný dekóderu spolu s vygenerovanými tokenmi. Rozdiel medzi výstupom z enkódera a pôvodným textom sa použije na trénovanie enkódera. Korupcia vstupu prebieha pomocou rôznych metód: zamaskovanie tokenov, vymazanie tokenov, doplnenie textu, permutácia vety, rotácia dokumentu.

BART môže byť použitý na:
 - klasifikáciu sekvencie - k vstupu pridáme špeciálny token, ktorý je nahradený výsledkom klasifikácie; vstup nie je skorumpovaný.
 - klasifikáciu tokenov - model priamo použije generované reprezentácie na predikciu pre každý token.
 - generovanie sekvencie - prebieha viac ako sumarizácia, kde je najprv spracovaný celý vstup a následne sa vygeneruje reakcia.
 - strojový preklad - celý BART model je použitý ako čistý predtrénovaný dekóder, a k nemu je pridaný nový enkóder s náhodnými váhami. Nová štruktúra je potom dotrénovaná najprv s freezenutými váhami dekódera, a následnou aktualizáciou všetkých parametrov.

## Príklady

* [Generovanie textu pomocou GPT-2](https://github.com/rasbt/machine-learning-book/blob/main/ch16/ch16-part2-gpt2.ipynb)
* [Dotrénovanie BERT modelu](https://github.com/rasbt/machine-learning-book/blob/main/ch16/ch16-part3-bert.ipynb)

## Použité zdroje

* Bahdanau, Dzmitry, Kyunghyun Cho, and Yoshua Bengio. "Neural machine translation by jointly learning to align and translate." arXiv preprint arXiv:1409.0473 (2014).
* Vaswani, Ashish, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan N. Gomez, Łukasz Kaiser, and Illia Polosukhin. "Attention is all you need." Advances in neural information processing systems 30 (2017).
* Ba, Jimmy Lei, Jamie Ryan Kiros, and Geoffrey E. Hinton. "Layer normalization." arXiv preprint arXiv:1607.06450 (2016).
* Raschka, Sebastian, Yuxi Hayden Liu, Vahid Mirjalili, and Dmytro Dzhulgakov. Machine Learning with PyTorch and Scikit-Learn: Develop machine learning and deep learning models with Python. Packt Publishing Ltd, 2022. Kapitola 16

**GPT:**
* Radford, Alec, Karthik Narasimhan, Tim Salimans, and Ilya Sutskever. "Improving language understanding by generative pre-training." (2018).
* Radford, Alec, Jeffrey Wu, Rewon Child, David Luan, Dario Amodei, and Ilya Sutskever. "Language models are unsupervised multitask learners." OpenAI blog 1, no. 8 (2019): 9.
* Brown, Tom, Benjamin Mann, Nick Ryder, Melanie Subbiah, Jared D. Kaplan, Prafulla Dhariwal, Arvind Neelakantan et al. "Language models are few-shot learners." Advances in neural information processing systems 33 (2020): 1877-1901.
* Child, Rewon, Scott Gray, Alec Radford, and Ilya Sutskever. "Generating long sequences with sparse transformers." arXiv preprint arXiv:1904.10509 (2019).

**BERT:**
* Devlin, Jacob, Ming-Wei Chang, Kenton Lee, and Kristina Toutanova. "Bert: Pre-training of deep bidirectional transformers for language understanding." arXiv preprint arXiv:1810.04805 (2018).

**BART:**
* Lewis, Mike, Yinhan Liu, Naman Goyal, Marjan Ghazvininejad, Abdelrahman Mohamed, Omer Levy, Ves Stoyanov, and Luke Zettlemoyer. "Bart: Denoising sequence-to-sequence pre-training for natural language generation, translation, and comprehension." arXiv preprint arXiv:1910.13461 (2019).